import type { FactionId, LandRegion, Region } from '../types'
import { isLand } from '../types'

export const PULSES_PER_YEAR = 52
export const ANNUAL_POPULATION_GROWTH = 0.01
/** Effective tax rate at 100 Stability and 100% Popularity. */
export const MAX_TAX_RATE = 0.7

/** Computed fresh, never stored. */
export function perCapitaGdp(region: LandRegion): number {
  return region.population > 0 ? region.gdp / region.population : 0
}

/** 0 below 50% Popularity, scaling linearly to MAX_TAX_RATE at 100%. */
export function popularityCut(popularity: number): number {
  if (popularity <= 50) return 0
  return MAX_TAX_RATE * ((popularity - 50) / 50)
}

/** Money the controlling faction collects from a region each Pulse. 0 with no controller. */
export function moneyPerPulse(region: LandRegion): number {
  if (!region.controller) return 0
  return (region.gdp / PULSES_PER_YEAR) * (region.stability / 100) * popularityCut(region.popularity[region.controller])
}

/** Research generated by a region each Tick: GDP/1B × Stability/100. */
export function researchPerTick(region: LandRegion): number {
  return (region.gdp / 1e9) * (region.stability / 100)
}

/** Legitimacy a faction earns per Pulse: Σ popularity × population / 1M, across all land regions regardless of Control. */
export function legitimacyPerPulse(regions: Iterable<Region>, faction: FactionId): number {
  let total = 0
  for (const r of regions) {
    if (isLand(r)) total += (r.popularity[faction] / 100) * (r.population / 1e6)
  }
  return total
}

/** Flat 1% annual growth, applied per Pulse. */
export function populationGrowthPerPulse(population: number): number {
  return (population * ANNUAL_POPULATION_GROWTH) / PULSES_PER_YEAR
}
